name: algo-trader
services:
  ib-gateway:
    build:
      # Using latest tag for arm64 compatibility
      # Stable version is not compatible with arm64
      context: ./ib-gateway-docker/latest
      dockerfile: Dockerfile
    image: ${REGISTRY}/${IMAGE_NAME_LOWER}:latest-arm64
  novnc:
    build:
      context: .
      dockerfile: novnc.Dockerfile
    image: ${REGISTRY}/${IMAGE_NAME_LOWER}-novnc:latest-arm64
  python-service:
    build:
      context: ./python-service
      dockerfile: Dockerfile
    image: ${REGISTRY}/${IMAGE_NAME_LOWER}-python-service:latest-arm64
    environment:
      - PYTHON_ENV=production
    volumes:
      - ./scripts:/app/scripts
    command: ["python3", "/app/scripts/your_script.py"]
    depends_on:
      - ib-gateway