# values.yaml
image:
  repository: ghcr.io/gnzsnz/ib-gateway
  tag: "stable"
  pullPolicy: IfNotPresent


nameOverride: ""
fullnameOverride: ""

env:  
  - name: TRADING_MODE
    value: "live"
  - name: BYPASS_WARNING
    value: "yes"
  - name: TIME_ZONE
    value: "Europe/Paris"
  - name: TZ
    value: "Europe/Paris"
  - name: JAVA_HEAP_SIZE
    value: "1024"
  - name: TWS_SETTINGS_PATH
    value: "/config/ibgateway/Jts"      

serviceAccount:
  create: true
  name: ""
  annotations: {}


service:
  type: LoadBalancer
  ports:
    - name: tws
      port: 4001
      targetPort: 4003  # Changé de 4001 à 4003
      protocol: TCP
    - name: api
      port: 4002
      targetPort: 4004  # Changé de 4002 à 4004
      protocol: TCP
    - name: vnc
      port: 5900
      targetPort: 5900
      protocol: TCP
  annotations:
    tailscale.com/expose: "true"

# Ajoutez un readiness probe pour le container VNC
readinessProbe:
  tcpSocket:
    port: 5900
  initialDelaySeconds: 30
  periodSeconds: 10

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  storageClass: local-path
  size: 10Gi

# Configuration du namespace
namespace:
  name: "ib-gateway"


ingress:
  enabled: true
  className: "nginx"
  annotations:
    tailscale.com/expose: "true"
  hosts:
    paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: ibgateway
            port:
              number: 4001
      - path: /vnc
        pathType: Prefix
        backend:
          service:
            name: ibgateway-novnc
            port:
              number: 6080

# Configuration des secrets
secret:
  name: "ib-gateway-secrets"

# Configuration des ressources
resources:
  limits:
    cpu: "1"
    memory: "1Gi"
  requests:
    cpu: "500m"
    memory: "512Mi"

probes:
  liveness:
    enabled: false
    initialDelaySeconds: 5
    periodSeconds: 5
  readiness:
    enabled: false
    initialDelaySeconds: 5
    periodSeconds: 5

logging:
  level: debug

security:
  autoRestartOnDisconnect: true

# Configuration NoVNC
novnc:
  enabled: true
  image:
    repository: theasp/novnc
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: LoadBalancer  # Changer de ClusterIP à NodePort ou LoadBalancer
    port: 6080
  display:
    width: "1280"
    height: "720"

# Configuration VNC
vnc:
  enabled: true
  port: 5900
  password: "myVNCpass"

# Python Service Configuration
pythonService:
  enabled: true
  image:
    repository: ${REGISTRY}/${IMAGE_NAME_LOWER}-python-service
    tag: latest-arm64
    pullPolicy: Always
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "250m"
      memory: "256Mi"