# values.yaml
image:
  repository: ghcr.io/gnzsnz/ib-gateway
  tag: "stable"
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""
  annotations: {}

service:
  type: ClusterIP
  annotations: {}

persistence:
  enabled: false
  accessMode: ReadWriteOnce
  storageClass: standard
  size: 10Gi

# Configuration du namespace
namespace:
  name: "ib-gateway"

ingress:
  enabled: true
  className: "nginx"  # ou votre classe d'ingress préférée
  annotations: {}
  hosts:
    - host: ibgateway.local  # remplacez par votre nom d'hôte par défaut
      paths:
        - path: /
          pathType: Prefix
          port: 4002  # port API par défaut

# Configuration des secrets
secret:
  name: "ib-gateway-secrets"

# Configuration IB Gateway
ibgateway:
  mode: "paper"
  port: "4001"
  apiPort: "4002"
  timezone: "Europe/Paris"

probes:
  liveness:
    enabled: false
    initialDelaySeconds: 5
    periodSeconds: 5
  readiness:
    enabled: false
    initialDelaySeconds: 5
    periodSeconds: 5

logging:
  level: debug

security:
  autoRestartOnDisconnect: true

# Configuration NoVNC
novnc:
  enabled: true
  image:
    repository: theasp/novnc
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 6080
  display:
    width: "1280"
    height: "720"

# Configuration VNC
vnc:
  enabled: true
  port: "5900"
  password: "myVNCpass"