apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ib-gateway.name" . }}
  labels:
    app: {{ include "ib-gateway.name" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "ib-gateway.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "ib-gateway.name" . }}
    spec:
      {{- if .Values.nodeSelector }}
      nodeSelector:
        kubernetes.io/arch: {{ .Values.nodeSelector.type }}
      {{- end }}
      containers:
        - name: ib-gateway
          {{- if .Values.image }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy | default "Always" }}
          {{- end }}
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              {{- if .valueFrom }}
              valueFrom:
                {{- toYaml .valueFrom | nindent 16 }}
              {{- else if .value }}
              value: {{ .value | quote }}
              {{- end }}
            {{- end }}