# templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ib-gateway.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "ib-gateway.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "ib-gateway.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ib-gateway.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "ib-gateway.serviceAccountName" . }}
      containers:
        - name: ib-gateway
          image: {{ include "ib-gateway.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: tws
              containerPort: {{ .Values.ibgateway.port | int }}
              protocol: TCP
            - name: api
              containerPort: {{ .Values.ibgateway.apiPort | int }}
              protocol: TCP
            {{- if .Values.vnc.enabled }}
            - name: vnc
              containerPort: {{ .Values.vnc.port | int }}
              protocol: TCP
            {{- end }}
          env:
            - name: TWS_USERID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: username
            - name: TWS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: password
            - name: TRADING_MODE
              value: {{ .Values.ibgateway.mode | quote }}
            - name: TZ
              value: {{ .Values.ibgateway.timezone | quote }}
          envFrom:
            - configMapRef:
                name: {{ include "ib-gateway.fullname" . }}-config
          {{- if .Values.probes.readiness.enabled }}
          readinessProbe:
            tcpSocket:
              port: api
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
          {{- end }}
          {{- if .Values.probes.liveness.enabled }}
          livenessProbe:
            tcpSocket:
              port: api
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: data
              mountPath: /root/Jts
              subPath: config
            - name: data
              mountPath: /root/IBController/Logs
              subPath: logs
          {{- end }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "ib-gateway.fullname" . }}-pvc
      {{- end }}
