{{- if or .Values.ibgateway.env .Values.ibgateway.image -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ibgateway
spec:
  template:
    spec:
      containers:
        - name: ib-gateway
          {{- if .Values.ibgateway.image }}
          image: {{ .Values.ibgateway.image.repository }}:{{ .Values.ibgateway.image.tag }}
          imagePullPolicy: {{ .Values.ibgateway.image.pullPolicy | default "Always" }}
          {{- end }}
          
          {{- if or .Values.ibgateway.env .Values.ibgateway.secret }}
          env:
            {{- if .Values.ibgateway.secret }}
            - name: TWS_USERID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.ibgateway.secret.name }}
                  key: username
            - name: TWS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.ibgateway.secret.name }}
                  key: password
            {{- if .Values.ibgateway.secret.account }}
            - name: IB_ACCOUNT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.ibgateway.secret.name }}
                  key: account
            {{- end }}
            {{- end }}

            {{- if .Values.ibgateway.mode }}
            - name: TRADING_MODE
              value: {{ .Values.ibgateway.mode | quote }}
            {{- end }}

            {{- if .Values.ibgateway.timezone }}
            - name: TZ
              value: {{ .Values.ibgateway.timezone | quote }}
            - name: TIME_ZONE
              value: {{ .Values.ibgateway.timezone | quote }}
            {{- end }}

            {{- if .Values.ibgateway.javaHeapSize }}
            - name: JAVA_HEAP_SIZE
              value: {{ .Values.ibgateway.javaHeapSize | quote }}
            {{- end }}

            {{- with .Values.ibgateway.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}

          {{- if .Values.ibgateway.ports }}
          ports:
            {{- range .Values.ibgateway.ports }}
            - name: {{ .name }}
              containerPort: {{ .port }}
              {{- if .targetPort }}
              targetPort: {{ .targetPort }}
              {{- end }}
              protocol: {{ .protocol | default "TCP" }}
            {{- end }}
          {{- end }}

          {{- if .Values.ibgateway.resources }}
          resources:
            {{- toYaml .Values.ibgateway.resources | nindent 12 }}
          {{- end }}

          {{- if .Values.ibgateway.probes }}
          {{- with .Values.ibgateway.probes.liveness }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.ibgateway.probes.readiness }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
{{- end }}