apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ib-gateway.name" . }}
  labels:
    app: {{ include "ib-gateway.name" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "ib-gateway.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "ib-gateway.name" . }}
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: ib-gateway-files-config
        - name: config-storage
          persistentVolumeClaim:
            claimName: {{ include "ib-gateway.fullname" . }}-pvc
        - name: tmp-volume
          emptyDir: {}
        {{- if .Values.volumes }}
        {{- toYaml .Values.volumes | nindent 8 }}
        {{- end }}
      initContainers:
        - name: init-config
          image: busybox
          command:
            - /bin/sh
            - -c
            - |
              mkdir -p /config/ibgateway /config/ibc
              cp /config/templates/jts.ini.tmpl /config/ibgateway/
              cp /config/templates/config.ini.tmpl /config/ibc/
              chmod -R 777 /config/ibgateway /config/ibc
          volumeMounts:
            - name: config-volume
              mountPath: /config/templates
            - name: config-storage
              mountPath: /config/ibgateway
            - name: config-storage
              mountPath: /config/ibc
      containers:
        - name: ib-gateway
          {{- if .Values.image }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy | default "Always" }}
          {{- end }}
          volumeMounts:
            - name: config-storage
              mountPath: /config/ibgateway
            - name: config-storage
              mountPath: /config/ibc
            - name: tmp-volume
              mountPath: /tmp/.X11-unix
          securityContext:
            privileged: true
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              {{- if .valueFrom }}
              valueFrom:
                {{- toYaml .valueFrom | nindent 16 }}
              {{- else if .value }}
              value: {{ .value | quote }}
              {{- end }}
            {{- end }}