apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ib-gateway.fullname" . }}-python-service
  labels:
    {{- include "ib-gateway.labels" . | nindent 4 }}
    app.kubernetes.io/component: python-service
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "ib-gateway.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: python-service
  template:
    metadata:
      labels:
        {{- include "ib-gateway.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: python-service
    spec:
      containers:
        - name: python-service
          image: {{ .Values.pythonService.image.repository }}:{{ .Values.pythonService.image.tag }}
          imagePullPolicy: {{ .Values.pythonService.image.pullPolicy }}
          env:
            - name: PYTHON_ENV
              value: production
            - name: IB_GATEWAY_HOST
              value: {{ include "ib-gateway.fullname" . }}
            - name: IB_GATEWAY_PORT
              value: "{{ .Values.apiPort }}"
          volumeMounts:
            - name: scripts
              mountPath: /app/scripts
      volumes:
        - name: scripts
          configMap:
            name: {{ include "ib-gateway.fullname" . }}-python-scripts