apiVersion: v1
kind: Service
metadata:
  name: {{ include "ib-gateway.fullname" . }}
  labels:
    {{- include "ib-gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
      protocol: TCP
      name: tws
    - port: {{ .Values.apiPort }}
      targetPort: {{ .Values.apiPort }}
      protocol: TCP
      name: api
    {{- if .Values.vnc.enabled }}
    - port: {{ .Values.vnc.port }}
      targetPort: {{ .Values.vnc.port }}
      protocol: TCP
      name: vnc
    {{- end }}
  selector:
    {{- include "ib-gateway.selectorLabels" . | nindent 4 }}